// const dataType = {
//   title,
//   href,
//   img,
//   ott,
//   description,
//   film_rating,
//   year,
//   genre,
//   distributor,
//   season,
//   director,
//   cast,
//   original,
// };
export const tempData = [
  {
    title: "러블리 라이터",
    href: "https://www.tving.com/contents/P001616613",
    img: "https://image.tving.com/upload/cms/caip/CAIP0900/P001616613.jpg/dims/resize/480",
    ott: "TVING",
    description:
      '<p class="css-1ndhscg e1tfqgq925" style="-webkit-line-clamp: 3;">판타지 작가인 진이 쓴 BL 소설이 대형 방송사의 드라마로 제작되면서, 출판사 편집장은 또다시 진에게 BL 소설을 써 달라고 한다. 진은 편집장 부탁에 못 이겨 한 편만 더 쓰겠다고 승낙하고, 방송국 오디션에 참관하는데 넙십이라는 배우에게 봉변을 당한다. 넙십이 지낼 곳이 없다며 한 달만 같이 살아달라는 부탁을 하여 둘은 한집에서 같이 생활하게 되는데...</p>',
    film_rating: "15+",
    year: "2020",
    genre: "드라마",
    distributor: "엔케이컨텐츠",
    season: "시즌 1개",
    director: "번딧 신타나파라디",
    cast: "까오, 업",
    original: 0,
  },
  {
    title: "용사 요시히코와 악령의 열쇠",
    href: "https://www.tving.com/contents/P001500045",
    img: "https://image.tving.com/upload/cms/caip/CAIP0900/P001500045.jpg/dims/resize/480",
    ott: "TVING",
    description:
      "마왕을 봉인하고 100년이라는 시간이 흐른 어느 날, 누군가에 의해 봉인이 풀려 세상은 다시 한번 마물들의 공격을 받게 되었다.\r\n\r\n백성들은 과거 마왕을 봉인한 ′요시히코′라는 이름의 용사를 떠올리지만, 용사 요시히코는 먼 옛날 이미 세상을 떠난 후였고, 백성들은 절망에 울부짖는다.\r\n\r\n그때, 부처가 하늘에서 나타나 이 세상에 자비의 빛을 내리고, 용사 요시히코가 되살아난다!!\r\n\r\n그리고 부처는 요시히코에게 다시 한번 여행을 떠나 ′봉인의 열쇠′를 찾으라고 말한다!!",
    film_rating: "15+",
    year: "2012",
    genre: "드라마",
    distributor: "SPO KOREA",
    season: "시즌 3개",
    director: "후쿠다 유이치",
    cast: "야마다 타카유키, 타쿠마 신, 키나미 하루카, 무로 츠요시 사토 지로, 오카모",
    original: 0,
  },
];
